### ISSUE TITLE
cornerDetector detectAndCompute in windows and detect in android

### ISSUE THREAD

**Issue by deshan** [anandmuralidhar24/SimpleARAndroid#2] opened 2017-01-07 11:18 UTC
Hi Anand,

I tried to extract the orb keypoints in windows opencv program and tried to use them in android. But this works only if I get the traning image in android app by saving the _cameraImageForBack_ and use it in windows program.

But if tried to get the training image from else where and do the training in windows and then use the keypoints and image in android app it does not detect.

Any reason? May be because not maintaining the aspect ratio?

Thanks
chamika

**Comment by anandmuralidhar24** [comment] 2017-01-08 04:51
Hi chamika,

Both the aspect ratio and the size should match with that of the query image.

best,
Anand

**Comment by deshan** [comment] 2017-01-08 07:31
Hi Anand,

Thanks for the reply.

Is there a way to train a file image in the local storage? I tried below code. But not succeeded (Not detect)

   ```
  bool SimpleARClass::DetectKeypointsInReferenceImage() {
  
        cv::Mat image;
        image = cv::imread("/sdcard/DCIM/train.jpg", CV_LOAD_IMAGE_COLOR); 

        if(!image.data )
              return false;

        cornerDetector->detectAndCompute(image, cv::noArray(), referenceKeypoints, referenceDescriptors);
```

Any suggestion to match the size and aspect ratio before training  file image?

Thanks 
chamika

**Comment by anandmuralidhar24** [comment] 2017-01-08 07:44
You can print the size/aspect ratio of the images that you are getting as your camera's input feed. You can use `cameraImageForBack.rows`, `cameraImageForBack.cols`.
Then use an external program like gimp to match the size. You can match the aspect ratio by cropping the image - distorting the image will not allow you to match with a query image.

Then override the function as you have done, it should hopefully work. To debug, draw detected corners on `image` in above code and save it. See if the corners match with expected ones.

**Comment by deshan** [comment] 2017-01-08 07:51
Thanks Anand I will check

**Comment by deshan** [comment] 2017-01-08 09:50
Actually the problem was flipping. Once I did the fliiping of the training image, it successfully identifying.

As you said I need to do some experiments with the preview size and image size in order to calculate the correct homography.

Thanks Anand

**Comment by anandmuralidhar24** [comment] 2017-01-09 04:00
Ok great, please close the issue in case the problem is resolved.

best,
Anand

**Closed as completed** 2017-01-09 04:48 UTC
